In [1]:
#First Prediction for the Dataset
#Changing Dataframes and Arrays in order to get better outputs
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
X = iris.data
y = iris.target

In [1]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn = KNeighborsClassifier(n_neighbors=1)

In [8]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [9]:
knn.predict([[3, 5, 4, 2]])

array([2])

In [10]:
print("Predicted target name:",
       iris['target_names'][knn.predict([[3, 5, 4, 2]])])

Predicted target name: ['virginica']


In [11]:
X_new = np.array([[3, 5, 4, 2]])
print("X_new.shape:", X_new.shape)

X_new.shape: (1, 4)


In [12]:
mypredict = knn.predict(X_new)

In [13]:
print("Prediction:", mypredict)
print("Predicted target name:",
       iris['target_names'][mypredict])

Prediction: [2]
Predicted target name: ['virginica']


In [14]:
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

In [15]:
knn = KNeighborsClassifier(n_neighbors=3)

#Data in Model


In [16]:
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

#Prediction of Previous Values

In [17]:
knn.predict(X_new)

array([1, 1])

In [18]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X, y)
lr.predict(X_new)

array([2, 0])